//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StripeExample.Web.Data
{
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class PaymentsModel : DbContext, IPaymentsModel
    {
        public PaymentsModel()
            : base("name=PaymentsModel")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<Feature> Features { get; set; }
        public virtual DbSet<Plan> Plans { get; set; }
    }
}
